version: "3.9"

services:
  wordpress-db:
    image: mysql:5.7
    container_name: wordpress-db
    environment:
      - MYSQL_ROOT_PASSWORD=r00t
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=usr-wordpress
      - MYSQL_PASSWORD=pwd-wordpress
    networks:
      - wordpress_nginx
    ports:
      - "3306"
    restart: always

  wordpress1:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress1
    volumes:
      - ./www/html:/var/www/html
    links:
      - wordpress-db:mysql
    env_file:
      - .env
    networks:
      - wordpress_nginx
    depends_on:
      - "wordpress-db"
    restart: always

  wordpress2:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress2
    volumes:
      - ./www/html:/var/www/html
    links:
      - wordpress-db:mysql
    env_file:
      - .env
    networks:
      - wordpress_nginx
    depends_on:
      - "wordpress-db"
    restart: always

  wordpress3:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress3
    volumes:
      - ./www/html:/var/www/html
    links:
      - wordpress-db:mysql
    env_file:
      - .env
    networks:
      - wordpress_nginx
    depends_on:
      - "wordpress-db"
    restart: always

  nginx:
    container_name: nginx
    image: nginx:1.19.0
    networks:
      - "wordpress_nginx"
    depends_on:
      - "wordpress1"
      - "wordpress2"
      - "wordpress3"
      - "wordpress-db"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www/html:/usr/share/nginx/html
    ports:
      - "80:80"

  locust:
    container_name: locust
    image: grubykarol/locust
    environment:
      - ATTACKED_HOST=http://localhost/
      - LOCUST_OPTS="-c 10 -r 10"
      - LOCUST_FILE=./locustTest.py
    volumes:
      - ./locustfile.py:/mnt/locust/
    depends_on:
      - "nginx"
    ports:
      - "8089:8089"

networks:
  wordpress_nginx:
    driver: bridge
