version: "3.9"

services:
  mysql:
    image: mysql:5.7
    container_name: wordpress-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=usr-wordpress
      - MYSQL_PASSWORD=pwd-wordpress
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  wordpress-1:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress1
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_nginx
    ports:
      - "8000:80"
    depends_on:
      - "mysql"
    restart: always

  wordpress-2:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress2
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_nginx
    depends_on:
      - "mysql"
    restart: always

  wordpress-3:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress3
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_nginx
    depends_on:
      - "mysql"
    restart: always

  nginx:
    container_name: nginx
    image: nginx:1.19.0
    networks:
      - "wordpress_nginx"
    depends_on:
      - "wordpress1"
      - "wordpress2"
      - "wordpress3"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/www/html:/usr/share/nginx/html
    ports:
      - "5000:5000"

networks:
  wordpress_nginx:
    driver: bridge

volumes:
  db_data: {}
  wordpress_data: {}